# Docker on Windows Server

# SQL Server 2019 Windows container dockerfile
## Warning: Restarting windows container causes the machine key to change and hence if you have any encryption configured then restarting SQL On Windows containers
## breaks the encryption key chain in SQL Server. 

# Download the SQL Developer from the following location  https://go.microsoft.com/fwlink/?linkid=866662 and extract the .box and .exe files using the option: "Download Media"

# BASED ON:
# - https://github.com/microsoft/mssql-docker
# - https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server



# FROM mcr.microsoft.com/windows/servercore:ltsc2019
FROM mcr.microsoft.com/windows/servercore:ltsc2022

ENV sa_password="_" \
    attach_dbs="[]" \
    ACCEPT_EULA="_" \
    sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# make install files accessible
COPY start.ps1 /
WORKDIR /

RUN $setup = Join-Path $env:TEMP 'sqlsetup.exe'; \
        Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/?linkid=866662' -OutFile $setup -UseBasicParsing; \
        $process = Start-Process -Wait -FilePath $setup -ArgumentList @('/Quiet', '/Action=Download', '/Language=en-US', '/MediaType=CAB', '/MediaPath=c:\sqlmedia') -PassThru; \
        Start-Process -Wait -FilePath 'c:\sqlmedia\SQLServer2019-DEV-x64-ENU.exe' -ArgumentList @('/qs', '/x:c:\setup'); \
        Remove-Item -Path ('c:\sqlmedia') -Recurse -Force
RUN \setup\setup.exe /q /ACTION=Install /INSTANCENAME=MSSQLSERVER /FEATURES=SQLEngine,Tools /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\NETWORK SERVICE' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS; \
        Remove-Item -Path ('c:\setup') -Recurse -Force

RUN Stop-Service MSSQLSERVER ; \
        Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name tcpdynamicports -Value '' ; \
        Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name tcpport -Value 1433 ; \
        Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql15.MSSQLSERVER\mssqlserver\' -Name LoginMode -Value 2 ;

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
RUN choco upgrade ssms sqlpackage -y

HEALTHCHECK CMD [ "sqlcmd", "-Q", "select 1" ]

CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
